openapi: 3.0.3
info:
  title: ':no-translate[API] Яндекс Маркета для продавцов (Push-нотификации)'
  description: >
    Часть :no-translate[API] Яндекс Маркета для продавцов, отвечающая за
    нотификацию внешнего :no-translate[API] магазинов о событиях.
  version: LATEST
paths:
  /notification:
    $ref: paths/notification.yaml
